### ISSUE TITLE
Fresh React + NWjs project returns "Mismatched native Koffi modules"

### ISSUE THREAD

**Issue by TheoKoffem** [Koromix/koffi#130]
I'm trying to add koffi v2.7.3 to a fresh NWjs "create-nw-react-app" application (v5.0.0). As soon as koffi is imported to a component, it returns this error:

```
Mismatched native Koffi modules
    at ./node_modules/koffi/index.js (http://localhost:3000/static/js/bundle.js:6074:42)
    at options.factory (http://localhost:3000/static/js/bundle.js:42104:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:41545:32)
    at fn (http://localhost:3000/static/js/bundle.js:41762:21)
    at ./src/App.js (http://localhost:3000/static/js/bundle.js:64:63)
    at options.factory (http://localhost:3000/static/js/bundle.js:42104:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:41545:32)
    at fn (http://localhost:3000/static/js/bundle.js:41762:21)
    at ./src/index.js (http://localhost:3000/static/js/bundle.js:172:62)
    at options.factory (http://localhost:3000/static/js/bundle.js:42104:31)
```
Any help would be appreciated.

I'm using NodeJS v20.11.0 (current LTS), NPM v10.2.4

**Comment by Koromix** [comment]
This feels like a bundling issue and outside of this project. Closing, unless more information is provided.
