### ISSUE TITLE
can not find librbary

### ISSUE THREAD

**Issue by YJCCreateAHistory** [Koromix/koffi#208]
node:electron/js2c/renderer_init:2 Error: Failed to load shared library: libgdcmMSFF.so.3.0

**Comment by Koromix** [comment]
Not enough information. Is this a system-wide library? Where do the so file live?

If it lives in the current working directory, it won't work unless you ask for it with `koffi.load('./libgdcmMSFF.so.3.0')`, at least not on POSIX systems.

In short, and to simplify, unless the library lives in a system directory, you need to specify the explicit path.

**Comment by YJCCreateAHistory** [comment]
I use it on an arm64 computer(electron 28.3.1, node 16.20.1) and then I got this error

`
/home/uos/Desktop/app/dll/index.js:17 init rectification error Error: Failed to load shared library: libgdcmMSFF.so.3.0: Cannot open shared object file: There is no file or directory
    at obj.load (/home/uos/Desktop/app/ffi/index.js:480:27)
    at Object.<anonymous> (/home/uos/Desktop/app/dll/index.js:15:28)
    at Object.<anonymous> (/home/uos/Desktop/app/dll/index.js:185:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:30758)
    at Module.require (node:internal/modules/cjs/loader:1150:19)

node:electron/js2c/renderer_init:2 TypeError: Cannot read properties of undefined (reading 'func')
    at Object.<anonymous> (/home/uos/Desktop/app/dll/index.js:20:45)
    at Object.<anonymous> (/home/uos/Desktop/app/dll/index.js:185:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:30758)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
`

**Comment by Koromix** [comment]
There error message says it all, it's not finding the library (libgdcmMSFF.so.3.0) you want to load: "Cannot open shared object file: There is no file or directory".

Is it installed somewhere?

**Comment by YJCCreateAHistory** [comment]
I'm not sure, because it works fine on my amd64 computer. I want to make sure that koffi is relying on this so file

**Comment by Koromix** [comment]
I don't know where `libgdcmMSFF.so.3.0` comes from (was it installed by the OS? by a package manager? did you build it yourself? did you download it?).

Native shared libraries are architecture-specific. You can't load an x86_64 shared library on an ARM64 platform. You need an ARM64 build of `libgdcmMSFF.so`.
