### ISSUE TITLE
[BUG?] Prebuilt binaries may still not working

### ISSUE THREAD

**Issue by bakashigure** [Koromix/koffi#73]
koffi works on Node mode, but throw exceptions on electron.

env:
```
koffi: 2.5.16
Electron: 26.0.0
Node: v18.12.1
arch: x86_64
platform: windows
```

# In Electron
![image](https://github.com/Koromix/koffi/assets/33803916/ffc54b97-61d4-41ba-9fa9-007a896d04b2)

# in Node
![image](https://github.com/Koromix/koffi/assets/33803916/8efbb2a9-c114-4b81-83b7-a0a202580c9c)

I'm guessing it might be a problem with the prebuilt file, but when I try to compile it myself, I get the error.

Full Log on compile koffi
```ps
PS E:\Code\MaaAsstElectronUI\node_modules\koffi> node .\src\cnoke\cnoke.js -p . -d src/koffi
>> Using CMake binary: cmake
>> Node: 18.12.1
>> Target: win32_x64
>> Running configuration
Not searching for unused variables given on the command line.
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.36.32535.0
-- The CXX compiler identification is MSVC 19.36.32535.0
-- The ASM compiler identification is MSVC
-- Found assembler: D:/Programs/Visual Studio Community 2022/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Programs/Visual Studio Community 2022/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Programs/Visual Studio Community 2022/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: D:/Programs/Visual Studio Community 2022/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/ml64.exe
-- Configuring done (4.3s)
-- Generating done (0.0s)
-- Build files have been written to: E:/Code/MaaAsstElectronUI/node_modules/koffi/build/koffi/win32_x64/v18.12.1_x64
>> Running build
MSBuild version 17.6.3+07e294721 for .NET Framework

  1>Checking Build System
  Building Custom Rule E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/CMakeLists.txt
  Assembling E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\abi_x64_win_asm.asm...
MASM : warning A4018: invalid command-line option : /Zc:__cplusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32
_x64\v18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Z:__cplusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_
x64\v18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Z__cplusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x
64\v18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Z_cplusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x6
4\v18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Zcplusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64
\v18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Zlusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v
18.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Zusplus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v1
8.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Zlus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.1
2.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /Zus [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12
.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4200 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4458 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4706 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4100 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4127 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4702 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4201 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4018: invalid command-line option : /wd4324 [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18
.12.1_x64\koffi.vcxproj]
MASM : warning A4008: invalid command-line option value, default is used : /W [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\k
offi\win32_x64\v18.12.1_x64\koffi.vcxproj]
  koffi_unity.c
E:/Code/MaaAsstElectronUI/node_modules/koffi/build/koffi/win32_x64/v18.12.1_x64/win_delay_hook.c(1,1): warning C4819: The file cont
ains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E
:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
  koffi_unity.cpp
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/call.cc(1,1): warning C4819: The file contains a character that cannot b
e represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_
modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src/core/libcc/libcc.hh(1,1): warning C4819: The file contains a character that cannot
 be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\nod
e_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\call.hh(1,1): warning C4819: The file contains a character that cannot b
e represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_
modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\ffi.hh(1,1): warning C4819: The file contains a character that cannot be
 represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_m
odules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\util.hh(1,1): warning C4819: The file contains a character that cannot b
e represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_
modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/call.cc(1022,26): warning C4456: declaration of 'len' hides previous loc
al declaration [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/call.cc(1005,22): message : see declaration of 'len' [E:\Code\MaaAsstEle
ctronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/ffi.cc(1,1): warning C4819: The file contains a character that cannot be
 represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_m
odules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\parser.hh(1,1): warning C4819: The file contains a character that cannot
 be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\nod
e_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\win32.hh(1,1): warning C4819: The file contains a character that cannot
be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node
_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\errno.inc(1,1): warning C4819: The file contains a character that cannot
 be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\nod
e_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/parser.cc(1,1): warning C4819: The file contains a character that cannot
 be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\nod
e_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/util.cc(1,1): warning C4819: The file contains a character that cannot b
e represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronUI\node_
modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/../../src/core/libcc/libcc.cc(1,1): warning C4819: The file contains a chara
cter that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAs
stElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
  Cannot format floating point values correctly without Dragonbox
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/../../src/core/libcc/libcc.cc(5654,49): warning C4244: 'argument': conversio
n from 'RG::Size' to 'int', possible loss of data [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\
koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/abi_x64_win.cc(1,1): warning C4819: The file contains a character that c
annot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaAsstElectronU
I\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:\Code\MaaAsstElectronUI\node_modules\koffi\src\koffi\src\trampolines/prototypes.inc(1,1): warning C4819: The file contains a char
acter that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [E:\Code\MaaA
sstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/abi_x64_win.cc(198,36): warning C4457: declaration of 'func' hides funct
ion parameter [E:\Code\MaaAsstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
E:/Code/MaaAsstElectronUI/node_modules/koffi/src/koffi/src/abi_x64_win.cc(66,44): message : see declaration of 'func' [E:\Code\MaaA
sstElectronUI\node_modules\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
LINK : fatal error LNK1104: cannot open file 'koffi.dir\RelWithDebInfo\abi_x64_win_asm.obj' [E:\Code\MaaAsstElectronUI\node_modules
\koffi\build\koffi\win32_x64\v18.12.1_x64\koffi.vcxproj]
Error: Failed to run build step
    at Builder.build (E:\Code\MaaAsstElectronUI\node_modules\koffi\src\cnoke\src\builder.js:255:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (E:\Code\MaaAsstElectronUI\node_modules\koffi\src\cnoke\cnoke.js:145:9)
PS E:\Code\MaaAsstElectronUI\node_modules\koffi>
```

**Comment by Koromix** [comment]
Indeed, this Windows nightmare never ends... :p

Koffi 2.5.18 seems to work with Node, Electron and NW.js
I'll add some tests to make sure this does not regress in the future.
